# Generated by Django 2.2.3 on 2019-07-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtrade', '0003_auto_20190730_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
