# Generated by Django 2.2.3 on 2019-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtrade', '0006_player_telf'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='changelist',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
