# Generated by Django 2.2.3 on 2019-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtrade', '0007_auto_20190730_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='idbgg',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
