# Generated by Django 2.2.3 on 2019-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtrade', '0008_auto_20190731_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='imageurl',
            field=models.URLField(blank=True, default=''),
        ),
    ]
