# Generated by Django 2.2.3 on 2019-08-01 07:36

from django.db import migrations, models
import localtrade.models


class Migration(migrations.Migration):

    dependencies = [
        ('localtrade', '0009_game_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='changelist',
            field=models.CharField(blank=True, default='', max_length=500, validators=[localtrade.models.validate_checklist]),
        ),
    ]
